version: '2.3'
services:
  arangodb:
    image: arangodb:3.10.5
    restart: unless-stopped
    environment:
      ARANGO_NO_AUTH: 1
      ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY: {{ARANGO_MEMORY}}
    networks:
      - {{NETWORK}}
    volumes:
      - db3:/var/lib/arangodb3
      - data:/arango/db
      - ./config:/arango/config
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    expose:
      - "8529"
    mem_limit: {{ARANGO_MEMORY}}

networks:
  {{NETWORK}}:
    external: true
volumes:
  db3:
  data:
